name: Build Deploy


# We are triggering the action on any push to git
on:
  pull_request:
    branches:
      - dev

env:
  ACTIONS_RUNNER_DEBUG: true

# We defined our jobs.
# For simplicity we will use a single job called build
jobs:
  build:
    # We specify what image to use. Can be also Mac or Windows.
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      # Step 1: checkout the code from git
      - uses: actions/checkout@v3

      # Step 2: Set up the JVM need to build our application
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
      # Step 3: run gradle build
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          export GRADLE_USER_HOME=$HOME/.gradle
          ./gradlew assemble

      # Step 4: login to docker hub using credentials set in github
      # secrets described in previous section
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 5: Set up QEMU in order to be able to run docker daemon
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Step 6: Set up docker build functionality
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      # Step 7: build docker image and push it to docker hub
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/toytopia-product:latest

      # Step 8: Authenticate to google cloud
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Step 9: Deploy our app to google cloud
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'toytopia-product'
          flags: '--allow-unauthenticated'
          image: '${{ secrets.DOCKERHUB_USERNAME }}/toytopia-product:latest'
          env_vars: |
            SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
            SPRING_DATASOURCE_PASSWORD=${{ secrets.JBDC_DATABASE_PASSWORD }}
            SPRING_DATASOURCE_USERNAME=${{ secrets.JBDC_DATABASE_USERNAME }}
            SPRING_DATASOURCE_URL=jdbc:postgresql://${{ secrets.JBDC_DATABASE_URL }}/postgres